[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info  
    Parsers_File parsers.conf

[INPUT]
    Name        syslog
    Mode        tcp
    Listen      0.0.0.0
    Port        514
    Parser      syslog-rfc3164

[OUTPUT]
    Name            stdout
    Match           *

[OUTPUT]
    Name            forward
    Match           *
    Host            192.168.1.22
    Port            5140
