module(load="imudp")
input(type="imudp" port="5141")

module(load="imtcp")
input(type="imtcp" port="5141")

template(name="RemoteLogs" type="string"
 string="/var/log/remote/%HOSTNAME%/%PROGRAMNAME%.log")
*.* ?RemoteLogs
*.* /dev/stdout
*.* @@192.168.1.22:5144
