[SERVICE]
    Flush        1
    Daemon       off
    Log-Level    info

[INPUT]
    Name         forward
    Listen       0.0.0.0
    Port         24220

[OUTPUT]
    Name         stdout
    Match        *

[OUTPUT]
    Name   remote
    Match  *
    Host   remote-machine's-ip
    Port   24224
